### PR TITLE
Force convert unsigned type to Bson signed type

### PR DESCRIPTION
**Pull request by zonyitoo**
* Serialize `u32` to `Bson::I32`
* Serialize `u64` to `Bson::I64`
* Serialize `u16` to `Bson::I32`
* Serialize `u8` to `Bson::I32`

Ref: #70

### CODE REVIEW

**Comment by saghm** [comment]
Wouldn't the 32- and 64-bit cases have the potential to overflow? I'm not sure what the correct solution for u64 is, but at the very least, I think that u32 should be serialized to i64, or else numbers larger 2^31 - 1 will not work as expected.

**Comment by zonyitoo** [comment]
Well, `i32` and `u32` has exactly the same size, so I think it is Ok to save `u32` value in a `i32` type. BSON doesn't support any unsigned types in specification, but just like other languages, such as Java, there are still lots of ways to work around it.

**Comment by kyeah** [comment]
@saghm is correct; unsigned 32-bit ints can hold larger numbers than signed 32-bits, since no bits need to be reserved to indicate the sign value. Converting them directly to same-bit signed integers has the potential for overflow.

The root issue lies with the fact that any sort of support for unsigned values on the driver-side will require conversions to supported types, and we shouldn't be making implicit conversion choices on our end for the user. Even if we implement hacks like serializing u32s as i64s, it's unclear to the user that this is happening, and the Rust struct they are using is the only source of truth of whether that value should be a u32 or an i64. 

This is especially problematic when you consider that many different applications may read from that database/dataset; consider a user who may not know that mongodb doesn't support unsigned types, and does not realize they have been writing i64s to the database until they read that data back from another app.

The correct approach is to drop support for auto-serializing unsigned values entirely (including converting them to floating points); rather, we should provide informative errors + custom field serializers so that the user:

1. understands that unsigned values are not supported / directly written to mongodb.
2. is able to remediate and _opt in_ to a number of different conversion options, depending on their application context and requirements. Those options include: promotions to a signed value with a higher bit count, or using FloatingPoint if they have u64s and don't require exact-precision values.

```rust
#[derive(Serialize)]
struct MyThinger {
    #[serde(serialize_with = "bson::serde::serialize_i64")]
    id: u32,
}
```

See documentation for: [field attributes](https://serde.rs/field-attrs.html) and [type bound example using deserialize_with](https://serde.rs/attr-bound.html).

**Comment by zonyitoo** [comment]
Hmm, so we should explicitly deny serializing unsigned types to BSON.

**Comment by marcelgarus** [comment]
> ```rust
> #[serde(serialize_with = "bson::serde::serialize_i64")]
>     id: u32,
> ```

I'm trying to achieve exactly this. Is there an actual easy solution to serialize `u32` as `i64`? I can't find serializer methods anywhere in the `bson` crate…

**Comment by flisky** [comment]
Are you looking for [serialize_u32_as_i64](https://docs.rs/bson/1.2.2/bson/serde_helpers/fn.serialize_u32_as_i64.html), @marcelgarus ?

**Comment by marcelgarus** [comment]
Ah yes, thank you

**Pull request closed without merging**
