### PR TITLE
Fix for #116

### PR DESCRIPTION
**Pull request by stusmall**
This PR adds a simple fuzzer, one failing test case I found with it and a what I think could be a fix.  I don't know BSON's wire protocol well, so my fix should be treated as suspect.

### CODE REVIEW

**Comment by stusmall** [comment]
Don't mind my amends.  :)  I wasn't sure on what the correct upper bound is, but I've got it now.  The spec didn't call it out so I ended up looking into some official mongo repos to see what they use for this case.

**Comment by zonyitoo** [comment]
Why I saw some `fuzz` folders in this commit?

**Comment by stusmall** [comment]
Those are generated by https://github.com/rust-fuzz/cargo-fuzz.  I thought it could be useful to have those tools available to continue to test with but I'd happily remove them.

**Comment by zonyitoo** [comment]
Why you set `MAX_BSON_SIZE: i32 = 16 * 1024 * 1024`?

**Comment by stusmall** [comment]
I originally pulled it from the source for bsondump from mongo, but they have this restraint in a lot of their code.  
https://github.com/mongodb/mongo-tools/blob/7722e31702b8d5f41520487a5197dd6202f75534/common/lldb/db.go#L38
https://github.com/mongodb/mongo-tools/blob/217728df376760cc66c93268fb50b7eca399572c/common/db/db.go#L38

This limit is what keeps bsondump from choking on this input.

It is also mentioned in the docs:  
https://docs.mongodb.com/manual/reference/limits/#BSON-Document-Size

This is a restraint set out by mongodb and not in the bson spec but AFAIK bson was made for mongo and mongo is its only user.

**Comment by stusmall** [comment]
Let me know if you want me to remove the fuzz code.  I'm happy to.

**Comment by zonyitoo** [comment]
Nope. Just leave it there.

**Pull request merged**
