### PR TITLE
Update serde to 0.7

### PR DESCRIPTION
**Pull request by kyeah**
Updates serde to 0.7. As noted in #24, this is a breaking change :(

### CODE REVIEW

**Comment by dariusc93** [comment]
Strange.. When I apply the patches to the local repo i have of bson-rs i get the following when compiling an example made with the sample code on #24

```
expected `core::option::Option<bson::ordered::OrderedDocument>`,
    found `core::option::Option<bson::ordered::OrderedDocument>`
(expected struct `bson::ordered::OrderedDocument`,
    found a different struct `bson::ordered::OrderedDocument`)
```

There are also other related errors. I will run a split test from my own workspace to see if its my code or this pr.

**Comment by zonyitoo** [comment]
I didn't use that in my own project. So I am Ok with this change.

Is it ready to be merged?

**Comment by dariusc93** [comment]
It's good so far for me.

**Comment by kyeah** [comment]
Yeah, this is ready for merging! Once this is in, I'll make the required changes on the mongo driver.

**Pull request merged**
